### ISSUE TITLE
Barras de rolagem

### ISSUE THREAD

**Issue by HCley** [ES-PUCRS/Pinguins_da_PUC#15]
As paginas estão apresentando uma barra de rolagem. Não deveria :)

**Comment by HCley** [comment]
Erro nas linhas 249 e 250 do arquivo style.css.
primeira resolução: remover as duas linhas.

**Comment by HCley** [comment]
Adicionar o parâmetro  { overflow: hidden; } na classe body do style.css

**Comment by gustavogallarreta** [comment]
#16 resolvido issue no pull request
